export const jobListing = [
  {
    id: "d6e15727-9fe1-4961-8c5b-ea44a9bd81aa",
    title: "Frontend Developer",
    company: "Evil Rabbit Corp",
    jobType: "Penuh Waktu",
    location: "On-site • Jakarta",
    category: "Development & IT",
    salary: "Negotiable",
    image_url: "/companies/evil-rabbit-corp.png",
    description: [
      "Mengembangkan dan memelihara antarmuka pengguna web.",
      "Bekerja sama dengan tim desain untuk menciptakan pengalaman pengguna yang optimal.",
      "Mengoptimalkan performa aplikasi untuk responsivitas yang lebih baik.",
      "Mengintegrasikan API backend ke dalam aplikasi frontend.",
    ],
    requirements: [
      "Pengalaman minimal 2 tahun dalam pengembangan frontend.",
      "Menguasai React.js, Next.js, dan Tailwind CSS.",
      "Memahami RESTful API dan integrasinya di frontend.",
      "Memiliki portofolio proyek frontend yang dapat ditunjukkan.",
    ],
  },
  {
    id: "3958dc9e-712f-4377-85e9-fec4b6a6442a",
    title: "Backend Developer",
    company: "Delba de Oliveira Ltd.",
    jobType: "Penuh Waktu",
    location: "On-site • Bandung",
    category: "Development & IT",
    salary: "Negotiable",
    image_url: "/companies/delba-de-oliveira-ltd.png",
    description: [
      "Membangun dan memelihara API serta layanan backend.",
      "Mengoptimalkan performa database dan sistem backend.",
      "Bekerja sama dengan tim frontend untuk integrasi sistem.",
      "Menjaga keamanan data dan sistem aplikasi.",
    ],
    requirements: [
      "Pengalaman minimal 3 tahun dalam pengembangan backend.",
      "Menguasai Node.js, Express, dan PostgreSQL.",
      "Memahami arsitektur microservices dan DevOps.",
      "Pengalaman dalam mengelola sistem cloud (AWS/GCP) lebih disukai.",
    ],
  },
  {
    id: "3958dc9e-742f-4377-85e9-fec4b6a6442a",
    title: "UI/UX Designer",
    company: "Lee Robinson Solutions",
    jobType: "Remote",
    location: "Remote • Jakarta",
    category: "Design & Creative",
    salary: "Negotiable",
    image_url: "/companies/lee-robinson-solutions.png",
    description: [
      "Mendesain wireframe dan prototype untuk aplikasi web dan mobile.",
      "Melakukan riset pengguna untuk meningkatkan pengalaman pengguna.",
      "Berkolaborasi dengan tim frontend dan backend dalam implementasi desain.",
      "Membuat guideline UI untuk menjaga konsistensi desain produk.",
    ],
    requirements: [
      "Pengalaman minimal 2 tahun dalam desain UI/UX.",
      "Menguasai Figma, Sketch, atau Adobe XD.",
      "Memahami prinsip-prinsip UX dan usability testing.",
      "Mampu membuat prototype interaktif.",
    ],
  },
  {
    id: "76d65c26-f784-44a2-ac19-586678f7c2f2",
    title: "Product Manager",
    company: "Michael Novotny Enterprises",
    jobType: "Penuh Waktu",
    location: "On-site • Surabaya",
    category: "Product & Marketing",
    salary: "Negotiable",
    image_url: "/companies/michael-novotny-enterprises.png",
    description: [
      "Mengelola roadmap produk dan strategi pengembangannya.",
      "Bekerja sama dengan tim teknis dan bisnis untuk eksekusi produk.",
      "Menganalisis data dan feedback pengguna untuk pengembangan produk.",
      "Memastikan produk sesuai dengan kebutuhan pasar.",
    ],
    requirements: [
      "Pengalaman minimal 3 tahun sebagai Product Manager.",
      "Memiliki pemahaman yang kuat tentang strategi produk dan UX.",
      "Mampu menggunakan alat analitik seperti Google Analytics dan Mixpanel.",
      "Komunikatif dan mampu bekerja dalam tim.",
    ],
  },
  {
    id: "CC27C14A-0ACF-4F4A-A6C9-D45682C144B9",
    title: "Data Analyst",
    company: "Amy Burns Group",
    jobType: "Hybrid",
    location: "Hybrid • Yogyakarta",
    category: "Data & Analytics",
    salary: "Rp10.000.000 - Rp15.000.000",
    image_url: "/companies/amy-burns-group.png",
    description: [
      "Mengumpulkan dan menganalisis data untuk pengambilan keputusan bisnis.",
      "Membuat dashboard dan laporan untuk visualisasi data.",
      "Mengembangkan model prediktif berdasarkan data historis.",
      "Berkoordinasi dengan tim bisnis untuk menyajikan insight berbasis data.",
    ],
    requirements: [
      "Pengalaman minimal 2 tahun sebagai Data Analyst.",
      "Menguasai SQL, Python, dan alat visualisasi data (Tableau/Power BI).",
      "Memahami konsep statistik dan machine learning dasar.",
      "Mampu menginterpretasikan data dengan baik.",
    ],
  },
  {
    id: "13D07535-C59E-4157-A011-F8D2EF4E0CBB",
    title: "Software Engineer",
    company: "Balazs Orban Co.",
    jobType: "Penuh Waktu",
    location: "On-site • Bali",
    category: "Development & IT",
    salary: "Rp12.000.000 - Rp18.000.000",
    image_url: "/companies/balazs-orban-co.png",
    description: [
      "Membangun dan mengembangkan sistem perangkat lunak skala besar.",
      "Bekerja sama dengan tim produk dan desain dalam implementasi fitur.",
      "Menulis kode yang bersih, efisien, dan terdokumentasi.",
      "Melakukan debugging dan pengujian aplikasi.",
    ],
    requirements: [
      "Pengalaman minimal 3 tahun sebagai Software Engineer.",
      "Menguasai JavaScript, TypeScript, dan framework seperti React atau Vue.",
      "Memahami konsep CI/CD dan software development lifecycle.",
      "Memiliki pengalaman dengan cloud computing (AWS/GCP).",
    ],
  },
];
